### ISSUE TITLE
Python 3.9 Binaries

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/DracoPy#13]

**Comment by manuel-castro** [comment]
Now available for Linux and OS X. Windows 3.9 binaries on hold until Appveyor supports it.

**Comment by william-silversmith** [comment]
Looks like AppVeyor supports 3.9 but you have to specify Visual Studio 2019.

https://github.com/computationalmodelling/nbval/pull/159/files

**Comment by william-silversmith** [comment]
Done!
