### ISSUE TITLE
Windows Binaries

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/DracoPy#15]
Hi Manuel!

I was building Kimimaro on Windows which has a (dumb, but annoying to remove) CloudVolume dependency. Unfortunately, it looks like it was crashing while compiling DracoPy. Would you be able to release the Windows wheels?

Thanks!

**Comment by manuel-castro** [comment]
Hey Will,

Yes, I will do my best to build new binaries this week -- hopefully the Appveyor process is relatively painless this time around.

**Comment by manuel-castro** [comment]
Wheels now available for Windows except Python 3.9 still. Those are on hold until this PR for scikit-build which adds support for Visual Studio 2019 is merged: https://github.com/scikit-build/scikit-build/pull/526

**Comment by william-silversmith** [comment]
Thank you Manuel!

**Comment by william-silversmith** [comment]
Upload py39 windows binaries. Done!
