### ISSUE TITLE
setup_requires missing scikit-build

### ISSUE THREAD

**Issue by fcollman** [seung-lab/DracoPy#2]
this causes chained installations to fail because scikit-build isn't included.  For example, the current cloud-volume graphene branch fails on travis because it pulls in DracoPy as a dependency, but scikit-build isn't properly specified as needed for installation.

**Comment by manuel-castro** [comment]
DracoPy actually requires scikit-build before setup is run. The way it ensures this is in pyproject.toml, which when using pip >= 10 will install scikit-build first before setup. From what you're saying it sounds like cloud-volume should upgrade the pip version it uses in travis. But the error I see in the travis build here: https://travis-ci.org/seung-lab/cloud-volume/jobs/516436510 seems like it is able to run setup but fails in building the C++ library. It seems like the g++ version travis is using (4.8.4) is too old to build draco

**Comment by manuel-castro** [comment]
Regardless if this is causing development issues, maybe we can remove/comment out DracoPy from cloud-volume/graphene until this is fixed

**Comment by fcollman** [comment]
okay.. sounds good.. I'm going to do that now to speed some other mesh related development. Maybe we should just setup a seperate graphene-draco branch with the commits to integrate that, and we can keep merging graphene into graphene-draco till we get this sorted out.

**Comment by manuel-castro** [comment]
I fixed the CloudVolume graphene travis DracoPy build problems in this branch: https://github.com/seung-lab/cloud-volume/commits/macastro-graphene-draco

With this fix and the os x fixes, do you think we can add DracoPy back into cloudvolume/graphene?

**Comment by fcollman** [comment]
awesome.  I can confirm that on python 3.7 on my 10.14 mac os x machine i was able to do a pip install . and make it work.  oddly python setup.py install didn't work, but presumably we want this deployed on pypi anyway so that's how it will get rolled out.  If we can distribute making binary wheels available for people that would help as well.. i'm willing to build the python 3.7 and 3.6 on mac os x, if you setup a pypi package and add me as a authorized uploader (forrestc)... though maybe we can use travis to that for us in an automated way.

**Comment by manuel-castro** [comment]
OS X + linux wheels now up on PyPI! Travis builds OS X wheels, docker builds the linux wheels
