### ISSUE TITLE
Error in reshape

### ISSUE THREAD

**Issue by brossignol** [seung-lab/DracoPy#25]
In the code there is an error: 
https://github.com/seung-lab/DracoPy/blob/1d3057cd0498cae9d77033a65ca6ec88d3cd346a/src/DracoPy.pyx#L93-L94
A flat array cannot be resized to its own size multiplied by 3.

A good answer is:
`arr = arr.reshape((len(arr) // 3, 3)) `
or 
`arr = arr.reshape((-1, 3)) `

**Comment by william-silversmith** [comment]
Thank you, l'll fix this later today!

**Comment by william-silversmith** [comment]
Okay the new release is building. Will let you know when I've uploaded the new wheels.

**Comment by william-silversmith** [comment]
New wheels are uploaded! Thanks for letting me know!
