### ISSUE TITLE
How to build wheel on apple silicon?

### ISSUE THREAD

**Issue by Jecksu** [seung-lab/DracoPy#26]
Hello，I tried to use PyPI to install dracopy on my mac apple silicon directly but failed when "installing beckend dependencies". I think because some backend dependencis does have appropriate version for this architectrue.
Did anyone try to rebuild the wheel for macox of apple silicon？

**Comment by Jecksu** [comment]
here is error detail,a little bit long.
$ pip install DracoPy                    
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting DracoPy
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9e/cf/704c5a9b8ad996db8a92e84a614c1bd2b8378617336a9edc727e7d378109/DracoPy-1.0.1.tar.gz (29.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [460 lines of output]
      Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
      Collecting cmake<3.15
        Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a0/39/e4bec00ea6af540ce9b523ac3859d49ba6d4ca87ab8d3884e2a428643884/cmake-3.14.4.post1.tar.gz (28 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Building wheels for collected packages: cmake
        Building wheel for cmake (setup.py): started
        Building wheel for cmake (setup.py): still running...
        Building wheel for cmake (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [160 lines of output]
      
      
            --------------------------------------------------------------------------------
            -- Trying "Ninja" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            Not searching for unused variables given on the command line.
            -- The C compiler identification is AppleClang 13.0.0.13000029
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - done
            -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
            -- Detecting C compile features
            -- Detecting C compile features - done
            -- The CXX compiler identification is AppleClang 13.0.0.13000029
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- Configuring done
            -- Generating done
            -- Build files have been written to: /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_cmake_test_compile/build
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Ninja" generator - success
            --------------------------------------------------------------------------------
      
            Configuring Project
              Working directory:
                /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build
              Command:
                cmake /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-install/cmake/data -DPYTHON_EXECUTABLE:FILEPATH=/Users/sxd/Desktop/development/offscreen-render/env/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.10 -DPYTHON_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/opt/homebrew/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
      
            -- The CXX compiler identification is AppleClang 13.0.0.13000029
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- ***************************************************
            -- Build CMake from source: OFF
            -- ***************************************************
            -- SuperBuild - CMakeProject-src-download
            -- SuperBuild - CMakeProject-src-download - URL: https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4.tar.gz
            -- SuperBuild - CMakeProject-src-download - CMakeProject_SOURCE_DIR: /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/src
            -- SuperBuild - CMakeProject-binary-download
            -- SuperBuild - CMakeProject-binary-download - URL: https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Darwin-x86_64.tar.gz
            -- SuperBuild -   CMakePythonDistributions
            -- Configuring done
            -- Generating done
            CMake Warning:
              Manually-specified variables were not used by the project:
      
                PYTHON_EXECUTABLE
                PYTHON_INCLUDE_DIR
                PYTHON_LIBRARY
                PYTHON_VERSION_STRING
                SKBUILD
      
      
            -- Build files have been written to: /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build
            [1/25] Creating directories for 'CMakeProject-src-download'
            [1/25] Performing download step (download, verify and extract) for 'CMakeProject-src-download'
            -- Downloading...
               dst='/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/cmake-3.14.4.tar.gz'
               timeout='none'
               inactivity timeout='none'
            -- Using src='https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4.tar.gz'
            CMake Error at _skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/download-CMakeProject-src-download.cmake:170 (message):
              Each download failed!
      
                error: downloading 'https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4.tar.gz' failed
                      status_code: 35
                      status_string: "SSL connect error"
                      log:
                      --- LOG BEGIN ---
                        Trying 20.205.243.166:443...
      
              Connected to github.com (20.205.243.166) port 443 (#0)
      
              ALPN, offering h2
      
              ALPN, offering http/1.1
      
              successfully set certificate verify locations:
      
               CAfile: /etc/ssl/cert.pem
               CApath: none
      
              TLSv1.2 (OUT), TLS handshake, Client hello (1):
      
              [224 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Server hello (2):
      
              [70 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Certificate (11):
      
              [2358 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Server key exchange (12):
      
              [116 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Server finished (14):
      
              [4 bytes data]
      
              TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
      
              [37 bytes data]
      
              TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
      
              [1 bytes data]
      
              TLSv1.2 (OUT), TLS handshake, Finished (20):
      
              [16 bytes data]
      
              LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443
      
              Closing connection 0
      
      
      
                      --- LOG END ---
      
      
      
      
            [2/25] Creating directories for 'CMakeProject-binary-download'
            FAILED: CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/CMakeProject-src-download-download /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/CMakeProject-src-download-download
            cd /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -P /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/download-CMakeProject-src-download.cmake && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -P /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/verify-CMakeProject-src-download.cmake && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -P /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/extract-CMakeProject-src-download.cmake && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -E touch /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-src-download-prefix/src/CMakeProject-src-download-stamp/CMakeProject-src-download-download
            ninja: build stopped: subcommand failed.
            Traceback (most recent call last):
              File "/opt/homebrew/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 595, in setup
                cmkr.make(make_args, env=env)
              File "/opt/homebrew/lib/python3.9/site-packages/skbuild/cmaker.py", line 609, in make
                raise SKBuildError(
      
            An error occurred while building with CMake.
              Command:
                cmake --build . --target install --config Release --
              Source directory:
                /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e
              Working directory:
                /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build
            Please see CMake's output for more information.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cmake
        Running setup.py clean for cmake
      Failed to build cmake
      Installing collected packages: cmake
        Running setup.py install for cmake: started
        Running setup.py install for cmake: still running...
        Running setup.py install for cmake: finished with status 'error'
        error: subprocess-exited-with-error
      
        × Running setup.py install for cmake did not run successfully.
        │ exit code: 1
        ╰─> [261 lines of output]
            /Users/sxd/Desktop/development/offscreen-render/env/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
              warnings.warn(
      
      
            --------------------------------------------------------------------------------
            -- Trying "Ninja" generator
            --------------------------------
            ---------------------------
            ----------------------
            -----------------
            ------------
            -------
            --
            Not searching for unused variables given on the command line.
            -- The C compiler identification is AppleClang 13.0.0.13000029
            -- Detecting C compiler ABI info
            -- Detecting C compiler ABI info - done
            -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
            -- Detecting C compile features
            -- Detecting C compile features - done
            -- The CXX compiler identification is AppleClang 13.0.0.13000029
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- Configuring done
            -- Generating done
            -- Build files have been written to: /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_cmake_test_compile/build
            --
            -------
            ------------
            -----------------
            ----------------------
            ---------------------------
            --------------------------------
            -- Trying "Ninja" generator - success
            --------------------------------------------------------------------------------
      
            Configuring Project
              Working directory:
                /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build
              Command:
                cmake /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e -G Ninja -DCMAKE_INSTALL_PREFIX:PATH=/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-install/cmake/data -DPYTHON_EXECUTABLE:FILEPATH=/Users/sxd/Desktop/development/offscreen-render/env/bin/python -DPYTHON_VERSION_STRING:STRING=3.9.10 -DPYTHON_INCLUDE_DIR:PATH=/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -DPYTHON_LIBRARY:FILEPATH=/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/libpython3.9.dylib -DSKBUILD:INTERNAL=TRUE -DCMAKE_MODULE_PATH:PATH=/opt/homebrew/lib/python3.9/site-packages/skbuild/resources/cmake -DCMAKE_BUILD_TYPE:STRING=Release -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=12.0 -DCMAKE_OSX_ARCHITECTURES:STRING=arm64
      
            -- The CXX compiler identification is AppleClang 13.0.0.13000029
            -- Detecting CXX compiler ABI info
            -- Detecting CXX compiler ABI info - done
            -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
            -- Detecting CXX compile features
            -- Detecting CXX compile features - done
            -- ***************************************************
            -- Build CMake from source: OFF
            -- ***************************************************
            -- SuperBuild - CMakeProject-src-download
            -- SuperBuild - CMakeProject-src-download - URL: https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4.tar.gz
            -- SuperBuild - CMakeProject-src-download - CMakeProject_SOURCE_DIR: /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/src
            -- SuperBuild - CMakeProject-binary-download
            -- SuperBuild - CMakeProject-binary-download - URL: https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Darwin-x86_64.tar.gz
            -- SuperBuild -   CMakePythonDistributions
            -- Configuring done
            -- Generating done
            CMake Warning:
              Manually-specified variables were not used by the project:
      
                PYTHON_EXECUTABLE
                PYTHON_INCLUDE_DIR
                PYTHON_LIBRARY
                PYTHON_VERSION_STRING
                SKBUILD
      
      
            -- Build files have been written to: /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build
            [1/25] Creating directories for 'CMakeProject-src-download'
            [1/25] Performing download step (download, verify and extract) for 'CMakeProject-src-download'
            -- Downloading...
               dst='/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/cmake-3.14.4.tar.gz'
               timeout='none'
               inactivity timeout='none'
            -- Using src='https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4.tar.gz'
            -- [download 100% complete]
            -- [download 0% complete]
            -- [download 1% complete]
            -- [download 2% complete]
            -- [download 4% complete]
            -- [download 5% complete]
            -- [download 6% complete]
            -- [download 8% complete]
            -- [download 9% complete]
            -- [download 13% complete]
            -- [download 16% complete]
            -- [download 17% complete]
            -- [download 18% complete]
            -- [download 19% complete]
            -- [download 21% complete]
            -- [download 22% complete]
            -- [download 25% complete]
            -- [download 26% complete]
            -- [download 27% complete]
            -- [download 28% complete]
            -- [download 30% complete]
            -- [download 32% complete]
            -- [download 33% complete]
            -- [download 36% complete]
            -- [download 37% complete]
            -- [download 38% complete]
            -- [download 39% complete]
            -- [download 40% complete]
            -- [download 42% complete]
            -- [download 43% complete]
            -- [download 44% complete]
            -- [download 46% complete]
            -- [download 47% complete]
            -- [download 49% complete]
            -- [download 50% complete]
            -- [download 51% complete]
            -- [download 54% complete]
            -- [download 55% complete]
            -- [download 56% complete]
            -- [download 57% complete]
            -- [download 58% complete]
            -- [download 60% complete]
            -- [download 61% complete]
            -- [download 62% complete]
            -- [download 63% complete]
            -- [download 65% complete]
            -- [download 66% complete]
            -- [download 67% complete]
            -- [download 68% complete]
            -- [download 69% complete]
            -- [download 70% complete]
            -- [download 71% complete]
            -- [download 72% complete]
            -- [download 73% complete]
            -- [download 74% complete]
            -- [download 75% complete]
            -- [download 76% complete]
            -- [download 77% complete]
            -- [download 78% complete]
            -- [download 79% complete]
            -- [download 80% complete]
            -- [download 81% complete]
            -- [download 82% complete]
            -- [download 83% complete]
            -- [download 84% complete]
            -- [download 85% complete]
            -- [download 86% complete]
            -- [download 87% complete]
            -- [download 88% complete]
            -- [download 89% complete]
            -- [download 90% complete]
            -- [download 91% complete]
            -- [download 92% complete]
            -- [download 93% complete]
            -- [download 94% complete]
            -- [download 95% complete]
            -- [download 96% complete]
            -- [download 97% complete]
            -- [download 98% complete]
            -- [download 99% complete]
            -- [download 100% complete]
            -- verifying file...
                   file='/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/cmake-3.14.4.tar.gz'
            -- Downloading... done
            -- extracting...
                 src='/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/cmake-3.14.4.tar.gz'
                 dst='/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/src'
            -- extracting... [tar xfz]
            -- extracting... [analysis]
            -- extracting... [rename]
            -- extracting... [clean up]
            -- extracting... done
            [2/25] Creating directories for 'CMakeProject-binary-download'
            [3/25] Performing download step (download, verify and extract) for 'CMakeProject-binary-download'
            -- Downloading...
               dst='/private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/cmake-3.14.4-Darwin-x86_64.tar.gz'
               timeout='none'
               inactivity timeout='none'
            -- Using src='https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Darwin-x86_64.tar.gz'
            CMake Error at CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/download-CMakeProject-binary-download.cmake:170 (message):
              Each download failed!
      
                error: downloading 'https://github.com/Kitware/CMake/releases/download/v3.14.4/cmake-3.14.4-Darwin-x86_64.tar.gz' failed
                      status_code: 35
                      status_string: "SSL connect error"
                      log:
                      --- LOG BEGIN ---
                        Trying 20.205.243.166:443...
      
              Connected to github.com (20.205.243.166) port 443 (#0)
      
              ALPN, offering h2
      
              ALPN, offering http/1.1
      
              successfully set certificate verify locations:
      
               CAfile: /etc/ssl/cert.pem
               CApath: none
      
              TLSv1.2 (OUT), TLS handshake, Client hello (1):
      
              [224 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Server hello (2):
      
              [70 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Certificate (11):
      
              [2358 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Server key exchange (12):
      
              [115 bytes data]
      
              TLSv1.2 (IN), TLS handshake, Server finished (14):
      
              [4 bytes data]
      
              TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
      
              [37 bytes data]
      
              TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
      
              [1 bytes data]
      
              TLSv1.2 (OUT), TLS handshake, Finished (20):
      
              [16 bytes data]
      
              LibreSSL SSL_connect: Operation timed out in connection to github.com:443
      
              Closing connection 0
      
      
      
                      --- LOG END ---
      
      
      
      
            [9/25] Completed 'CMakeProject-src-download'
            FAILED: CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/CMakeProject-binary-download-download /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/CMakeProject-binary-download-download
            cd /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -P /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/download-CMakeProject-binary-download.cmake && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -P /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/verify-CMakeProject-binary-download.cmake && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -P /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/extract-CMakeProject-binary-download.cmake && /opt/homebrew/Cellar/cmake/3.22.2/bin/cmake -E touch /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build/CMakeProject-binary-download-prefix/src/CMakeProject-binary-download-stamp/CMakeProject-binary-download-download
            ninja: build stopped: subcommand failed.
            Traceback (most recent call last):
              File "/opt/homebrew/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 595, in setup
                cmkr.make(make_args, env=env)
              File "/opt/homebrew/lib/python3.9/site-packages/skbuild/cmaker.py", line 609, in make
                raise SKBuildError(
      
            An error occurred while building with CMake.
              Command:
                cmake --build . --target install --config Release --
              Source directory:
                /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e
              Working directory:
                /private/var/folders/1h/qgv80m110379kyjh4t4r92th0000gn/T/pip-install-j8ui3yea/cmake_ec27c06b043c4a20adda2be143d7fe2e/_skbuild/macosx-12.0-arm64-3.9/cmake-build
            Please see CMake's output for more information.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: legacy-install-failure
      
      × Encountered error while trying to install package.
      ╰─> cmake
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for output from the failure.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
(env)

**Comment by william-silversmith** [comment]
Hi Jecksu, 

We have MacOS x86_64 wheels built which can be used on Apple Silicon if you use a Rosetta2 enabled terminal. I just built and upload an arm64 wheel right now for python3.9 which you can use. However, that's not something I anticipate doing as a matter of course. This project is somewhat difficult to compile, so I'd recommend downloading the x86 wheels if you can.

https://www.byran.tech/html/how-to-make-a-rosetta-2-emulated-x86-terminal-on-arm-apple-silicon-chips.html

**Comment by Jecksu** [comment]
> Hi Jecksu,
> 
> We have MacOS x86_64 wheels built which can be used on Apple Silicon if you use a Rosetta2 enabled terminal. I just built and uploaded an arm64 wheel right now for python3.9 which you can use. However, that's not something I anticipate doing as a matter of course. This project is somewhat difficult to compile, so I'd recommend downloading the x86 wheels if you can.
> 
> https://www.byran.tech/html/how-to-make-a-rosetta-2-emulated-x86-terminal-on-arm-apple-silicon-chips.html
 Roseta way works perfectly! thank you very much ：）
