### ISSUE TITLE
Will this be available for Windows?

### ISSUE THREAD

**Issue by svolchkov** [seung-lab/DracoPy#3]
Alternatively, what is required to make it work under Windows?

Thank you.

**Comment by manuel-castro** [comment]
Hi there,

There are currently no plans to support Windows, but it shouldn't be too hard to make it work. If it doesn't work out of the box, you probably just need to fiddle with the settings in setup.py such as the library_link_args. If you manage to get it working, PRs are welcome!

**Comment by jliempt** [comment]
Hi @svolchkov, did you succeed by any chance?

**Comment by manuel-castro** [comment]
@william-silversmith and I gave this a shot a while back and unfortunately it was more difficult than I had hoped. I definitely want to look into it again at some point (scikit-build supports Windows so it should be doable) but for now I'd definitely recommend using say the Windows Subsystem for Linux if that's possible for you.

**Comment by svolchkov** [comment]
@jliempt  No, I haven't unfortunately. I needed a quick solution so I ended up calling some Javascript programs from my Python code to do Draco conversion. Might go back to it at some point.

**Comment by fcollman** [comment]
@svolchkov @jliempt I just submitted a PR #9 where I think i made the changes to make this possible to compile properly on windows.

**Comment by jliempt** [comment]
@fcollman Thanks a lot! It's working for me.

**Comment by svolchkov** [comment]
@fcollman Many thanks for this

**Comment by william-silversmith** [comment]
I think some FlyWire users are on Windows and are starting to use CloudVolume. If this is compiling on Windows now, you can use AppVeyor to generate the binaries. Here's a sample:https://github.com/seung-lab/connected-components-3d/blob/master/appveyor.yml

After AppVeyor runs, I click manually on each job and click the artifacts tab, download the binary, and then move it to my dists directory before uploading to PyPI. I'm sure there's a better solution but that gets things working for me.
