### ISSUE TITLE
Changes needed in setup.py in order to work with Python 3.11 on MacOS

### ISSUE THREAD

**Issue by mpottinger** [seung-lab/DracoPy#36]
I had to remove:
 from packaging.version import LegacyVersion

and all other lines depending on it in order to install for Python 3.11 on MacOS arm successfully.
Once I removed the cmake check, all worked fine.

**Comment by william-silversmith** [comment]
Hi, I just uploaded a wheel for python311. Let me know if that solves this problem for you.

**Comment by mpottinger** [comment]
It seems to install via Pip no problem at all now! Thanks!
setup.py from the git repo still seems to have the same issue, but problem solved for me anyway!
