### ISSUE TITLE
1.2.1 with Python3.11 to PYPI

### ISSUE THREAD

**Issue by huspspvf9212** [seung-lab/DracoPy#40]
Hi @william-silversmith 

Could you upload 1.2.1 with Python3.11 wheel to PYPI? This would be very helpful.

Thanks!

**Comment by william-silversmith** [comment]
Hi, I'm having some trouble getting the github action to run to completion. Will release once I can debug it.

**Comment by huspspvf9212** [comment]
Thanks!

**Comment by huspspvf9212** [comment]
@william-silversmith Seems github actions is still failing. Following is what chatGPT says, might be helpful

The error message you provided indicates that the command python -m pip wheel /project --wheel-dir=/tmp/cibuildwheel/built_wheel --no-deps failed with code 1.

There are a few reasons why this command could have failed, including:

Permission issues: It's possible that the user running the command doesn't have the necessary permissions to perform the operation. Try running the command with sudo or as an administrator.

Dependencies missing: The --no-deps flag in the command specifies that no dependencies should be installed. If the package you're trying to build requires dependencies that aren't already installed, the command will fail. Try removing the --no-deps flag to allow dependencies to be installed.

Issues with the package: It's possible that there are issues with the package itself that are causing the command to fail. Make sure that the package is installed correctly and that all required files are present.

Issues with the environment: There could be issues with the Python environment that you're using to run the command. Try creating a new virtual environment and running the command again.

It's difficult to say exactly what is causing the error without more information. You can try running the command again with the -v flag to enable verbose output, which might provide more details about the error. Alternatively, you can try searching for the error message online to see if others have encountered similar issues and found a solution.

**Comment by william-silversmith** [comment]
Hi, sorry for the delay! I just made a few updates and hopefully the build
is fixed. I'm just waiting to see how it goes. Once it's ready, just fix
the DracoPy.cpp conflict and we can proceed.

**Comment by william-silversmith** [comment]
This is on pypi!
