### ISSUE TITLE
Removal of DracoPy.cpp from this repository

### ISSUE THREAD

**Issue by hanseuljun** [seung-lab/DracoPy#41]
Thanks for this wonderful and useful library!

During the transition from a user via pypi to a more serious user building the package via source, I have noticed that the .cpp file generated from the .pyx file is included in the repository.

Given this .cpp can be derived from the .pyx file and how it exactly looks like depends on the system that built the .cpp file, I would like to suggest removing the .cpp file from this repository.

A search for an cython example repository also resulted in finding a .gitignore file with the .cpp file ignored. See interface.cpp ignored here.
https://gitlab.multiscale.utah.edu/mahanse/cmake-cpp-cython-python-demo/-/blob/master/.gitignore

**Comment by william-silversmith** [comment]
Hi hanseuljun, 

We recently switched to building with the pyx directly, so you're right this is pretty redundant. I removed it. Thanks for helping clean the project up!

Will

**Comment by hanseuljun** [comment]
Wow this is the quickest I've ever had a suggestion accepted! Really appreciate it!
