### ISSUE TITLE
compress .pcap file

### ISSUE THREAD

**Issue by visakhchikku** [seung-lab/DracoPy#47]
I have a .pcap file. Can i compress this using this code? if yes please help me to compress

**Comment by nkemnitz** [comment]
If `.pcap` refers to the Wireshark network traffic capture file format, then no. DracoPy is a wrapper for https://github.com/google/draco, which is intended for compressing [polygon meshes](https://en.wikipedia.org/wiki/Polygon_mesh) and [point clouds](https://en.wikipedia.org/wiki/Point_cloud).
