### ISSUE TITLE
Can it encode normal or uv?

### ISSUE THREAD

**Issue by xiazhibin** [seung-lab/DracoPy#5]

**Comment by manuel-castro** [comment]
It cannot, but this shouldn't be that much work to implement because draco itself does support encoding these as GeometryAttributes. This isn't a high priority for our lab as we are not using normal or uv in our meshes, but I'd be happy to review a PR if you'd like to take a stab at it yourself.

**Comment by xiazhibin** [comment]
Thanks

**Comment by manuel-castro** [comment]
Reopening this as it would be a useful feature for the wider world and maybe we would want it down the line. I'll take a stab at this when I find a good time to

**Comment by william-silversmith** [comment]
Normals are supported. UV is still TBD.

**Comment by MickaelP34** [comment]
It seems that decoding normals are supported but not encoding, isn't it ?
Is this improvement planned ?
Thanks

**Comment by eskjorg** [comment]
> Reopening this as it would be a useful feature for the wider world and maybe we would want it down the line. I'll take a stab at this when I find a good time to

Yes, this would be useful for the wider world! Reopen issue?
