### ISSUE TITLE
Pointcloud support

### ISSUE THREAD

**Issue by haehn** [seung-lab/DracoPy#6]
Hi,

Would it be possible to also wrap `encoder->EncodePointCloudToBuffer` ? Did you try it already?

Thanks so much!
Daniel

**Comment by manuel-castro** [comment]
It's definitely possible, and functionality I want to have. But I haven't tried it yet, and I'm not sure how much time I'll have to in the near future. If you want to give it a shot by all means! I imagine the code would be quite similar to `encode_mesh` in DracoPy.h

**Comment by haehn** [comment]
Thanks! I will take a look!

**Comment by manuel-castro** [comment]
Started working on this this weekend.. close to releasing a new version whenever I have a few hours to refactor and release

**Comment by haehn** [comment]
I did some work on this last week: https://github.com/haehn/DracoPy maybe its helpful

**Comment by haehn** [comment]
Encoding works already

**Comment by manuel-castro** [comment]
That's funny, we ended up doing almost exactly the same thing, whoops :sweat_smile: 

In this branch decoding and encoding works: https://github.com/seung-lab/DracoPy/tree/point_cloud_support

I just want to refactor it to reduce the duplicate code (working with meshes and point clouds are quite similar) before releasing it

Thank you for your help!

**Comment by haehn** [comment]
That is funny. Thanks! I do need generic point cloud support - not only x,y,z data. Will you include that as well?

**Comment by manuel-castro** [comment]
I'm planning on adding support for Generic, Texture, and Color attributes next after this. Not sure when exactly I'll be able to since I can only really work on this nights and weekends. Like before, feel free to give it a try.

**Comment by haehn** [comment]
I added support for generic encoding and for sequential point cloud encoding by modifying your code. Not the cleanest but it works :)
https://github.com/haehn/DracoPy/tree/generic_point_cloud

**Comment by manuel-castro** [comment]
Cool beans! By the way I refactored the code and published a new version to PyPI, so v0.0.14 is live with the point cloud support

**Comment by Shawnxm** [comment]
I am a rookie to point cloud compression. I see you guys are using .drc files for encoding/decoding. Is it possible to input binary point cloud (also generic, like xyzi instead of just xyz) for compression?

**Comment by danem** [comment]
Any update on this? DracoPy in this repo doesn't seem to read in color data from point clouds.

**Comment by william-silversmith** [comment]
I think color data is probably a kind of metadata. We have a PR for metadata here: https://github.com/seung-lab/DracoPy/pull/20 

I think we do have support for decoding point cloud geometry, but it's only the geometry.

**Comment by william-silversmith** [comment]
I believe this is now in DracoPy.
