### ISSUE TITLE
Encode .obj

### ISSUE THREAD

**Issue by josephwh** [seung-lab/DracoPy#7]
Hey, thanks for creating this.

I haven't been able to figure out how to load an .obj and encode it to .drc - is this possible?

Thanks,
Joseph.

**Comment by manuel-castro** [comment]
Hi Joseph,

Yes you can, although for now you need to use some other library to extract the vertices and faces from the obj file first. I'm sure there are several Python libraries that can do this but off the top of my head I know zmesh can (see https://github.com/seung-lab/zmesh/blob/34fb3babbdb1d6f5bd0a423722a6a1c21f680694/zmesh/mesh.py#L107). Once you have an array of vertices and another of faces, you can simply do:
`
encoded_mesh = DracoPy.encode_mesh_to_buffer(vertices, faces)
with open('my_mesh.drc', 'wb') as mesh_file:
    mesh_file.write(encoded_mesh)
`
